// <auto-generated />
namespace StudentComp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class f9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f9));
        
        string IMigrationMetadata.Id
        {
            get { return "202205071507199_f9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
